/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 * 该R为自动生成，但是无法直接引用！
 */

package com.jacky.commondraw.res;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static int brush_library_item_color=0x7f070000;
        public static int brush_library_item_press_color=0x7f070001;
        public static int gb_checked_color=0x7f070002;
        public static int gb_erase_radiobutton_checked_color=0x7f070003;
        public static int gb_function_bar_bg=0x7f070004;
        public static int pen_picker_nobg=0x7f070005;
        public static int pen_picker_selected_bg=0x7f070006;
        public static int select_view_frame_line_color=0x7f070007;
    }
    public static final class dimen {
        public static int gb_drawtoolspicker_x_offset=0x7f050006;
        public static int gb_drawtoolspicker_y_offset=0x7f050007;
        public static int gb_erasepopupwindow_erase_radionbutton_height=0x7f050008;
        public static int gb_erasepopupwindow_erase_radionbutton_margintop=0x7f050009;
        public static int gb_erasepopupwindow_height=0x7f05000a;
        public static int gb_erasepopupwindow_width=0x7f05000b;
        public static int gb_erasepopupwindow_x_offset=0x7f05000c;
        public static int gb_erasepopupwindow_y_offset=0x7f05000d;
        public static int gb_function_layout_height=0x7f05000e;
        public static int gb_function_layout_marginleft=0x7f05000f;
        public static int gb_function_view_marginleft=0x7f050010;
        public static int gb_function_view_width=0x7f050011;
        public static int preview_content_height=0x7f050000;
        public static int preview_content_width=0x7f050001;
        public static int preview_content_x=0x7f050002;
        public static int preview_content_y=0x7f050003;
        public static int preview_image_height=0x7f050004;
        public static int preview_image_width=0x7f050005;
        public static int select_view_frame_line_height=0x7f050012;
        public static int select_view_frame_line_intervals=0x7f050013;
        public static int select_view_frame_line_padding=0x7f050014;
        public static int select_view_frame_line_width=0x7f050015;
    }
    public static final class drawable {
        public static int autocrop_n=0x7f020000;
        public static int brush=0x7f020001;
        public static int brush_library_item_selector=0x7f020002;
        public static int color_frame_big=0x7f020003;
        public static int color_frame_n=0x7f020004;
        public static int color_frame_p=0x7f020005;
        public static int color_line_frame_shape=0x7f020006;
        public static int color_rainbow=0x7f020007;
        public static int color_selector=0x7f020008;
        public static int color_straw=0x7f020009;
        public static int color_straw_button_style=0x7f02000a;
        public static int color_thickness_dropdown_add_selector=0x7f02000b;
        public static int color_thickness_dropdown_close=0x7f02000c;
        public static int color_thickness_dropdown_delete_selector=0x7f02000d;
        public static int color_thickness_dropdown_style=0x7f02000e;
        public static int crop_selector=0x7f02000f;
        public static int done_n=0x7f020010;
        public static int dropdown_eraser=0x7f020011;
        public static int dropdown_eraser_middle_select=0x7f020012;
        public static int dropdown_r=0x7f020013;
        public static int edit_pic_delete=0x7f020014;
        public static int edit_pic_rotation=0x7f020015;
        public static int ep_delete_pop_d=0x7f020016;
        public static int ep_eraser1_d=0x7f020017;
        public static int ep_eraser1_p=0x7f020018;
        public static int ep_eraser2_d=0x7f020019;
        public static int ep_eraser2_p=0x7f02001a;
        public static int ep_eraser3_d=0x7f02001b;
        public static int ep_eraser3_p=0x7f02001c;
        public static int eraser_clear=0x7f02001d;
        public static int eraser_point1=0x7f02001e;
        public static int eraser_point2=0x7f02001f;
        public static int eraser_point3=0x7f020020;
        public static int freecrop_n=0x7f020021;
        public static int function_eraser2=0x7f020022;
        public static int function_pen1=0x7f020023;
        public static int function_pen2=0x7f020024;
        public static int function_pen3=0x7f020025;
        public static int function_pen4=0x7f020026;
        public static int function_pen5=0x7f020027;
        public static int function_pen6=0x7f020028;
        public static int gb_check_selector=0x7f020029;
        public static int gb_erase_radiobutton_selector=0x7f02002a;
        public static int gb_function_view_selector=0x7f02002b;
        public static int gb_redo_selector=0x7f02002c;
        public static int gb_sr_check_selector=0x7f02002d;
        public static int gb_undo_selector=0x7f02002e;
        public static int ic_mode_edit=0x7f02002f;
        public static int ic_omlet=0x7f020030;
        public static int ic_redo=0x7f020031;
        public static int ic_redo_d=0x7f020032;
        public static int ic_save=0x7f020033;
        public static int ic_send=0x7f020034;
        public static int ic_undo=0x7f020035;
        public static int ic_undo_d=0x7f020036;
        public static int ic_up=0x7f020037;
        public static int image_background_style=0x7f020038;
        public static int insert=0x7f020039;
        public static int library_ic=0x7f02003a;
        public static int mode_edit=0x7f02003b;
        public static int pen=0x7f02003c;
        public static int pen_scrollbar_bg=0x7f02003d;
        public static int pen_scrollbar_bg2=0x7f02003e;
        public static int pen_scrollbar_bg2_l_icon=0x7f02003f;
        public static int pen_scrollbar_bg2_r_icon=0x7f020040;
        public static int pen_scrollbar_bg_l_icon=0x7f020041;
        public static int pen_scrollbar_bg_r_icon=0x7f020042;
        public static int pen_scrollbar_btn=0x7f020043;
        public static int pencil=0x7f020044;
        public static int popup_pen1=0x7f020045;
        public static int popup_pen2=0x7f020046;
        public static int popup_pen3=0x7f020047;
        public static int popup_pen4=0x7f020048;
        public static int popup_pen5=0x7f020049;
        public static int popup_pen6=0x7f02004a;
        public static int popup_pen_add=0x7f02004b;
        public static int popup_pen_delete=0x7f02004c;
        public static int popup_pen_triangle=0x7f02004d;
        public static int popup_window_select_bottom=0x7f02004e;
        public static int popup_window_select_brush=0x7f02004f;
        public static int popup_window_select_top=0x7f020050;
        public static int redo=0x7f020051;
        public static int redo_d=0x7f020052;
        public static int send=0x7f020053;
        public static int transform_off=0x7f020054;
        public static int undo=0x7f020055;
        public static int undo_d=0x7f020056;
    }
    public static final class id {
        public static int SRCheckBox=0x7f080035;
        public static int SRLayout=0x7f080034;
        public static int addImageView=0x7f080036;
        public static int add_brush=0x7f08000b;
        public static int alpha_percentage=0x7f08001c;
        public static int alpha_text=0x7f08001b;
        public static int auto_crop=0x7f080004;
        public static int back_title=0x7f080044;
        public static int brushRadioButton=0x7f080032;
        public static int brushRadioGroup=0x7f080031;
        public static int brush_color_thickness_layout=0x7f08000d;
        public static int brush_edit_dialog_close=0x7f080008;
        public static int brush_image=0x7f080000;
        public static int brush_library=0x7f080009;
        public static int brush_library_view=0x7f08002f;
        public static int brush_preview=0x7f080001;
        public static int brush_select_layout=0x7f080012;
        public static int cancel_btn=0x7f08004a;
        public static int color_picker_view=0x7f08002e;
        public static int color_picker_view_parent=0x7f08002d;
        public static int color_select_layout=0x7f08001e;
        public static int crop_content=0x7f080007;
        public static int doodleView=0x7f08003f;
        public static int drawActionBarLayout=0x7f080030;
        public static int edit_cancel=0x7f080005;
        public static int edit_done=0x7f080006;
        public static int edit_image=0x7f080045;
        public static int editor_func_color_A=0x7f08001f;
        public static int editor_func_color_B=0x7f080020;
        public static int editor_func_color_C=0x7f080021;
        public static int editor_func_color_D=0x7f080022;
        public static int editor_func_color_E=0x7f080023;
        public static int editor_func_color_F=0x7f080024;
        public static int editor_func_color_G=0x7f080025;
        public static int editor_func_color_H=0x7f080026;
        public static int editor_func_color_I=0x7f080027;
        public static int editor_func_color_J=0x7f080028;
        public static int editor_func_color_K=0x7f080029;
        public static int editor_func_color_L=0x7f08002b;
        public static int editor_func_color_M=0x7f08002a;
        public static int editor_func_color_straw=0x7f08002c;
        public static int editor_func_d_brush_mark=0x7f080018;
        public static int editor_func_d_brush_markpen=0x7f080016;
        public static int editor_func_d_brush_normal=0x7f080015;
        public static int editor_func_d_brush_scribble=0x7f080014;
        public static int editor_func_d_brush_sketch=0x7f080013;
        public static int editor_func_d_brush_writingbrush=0x7f080017;
        public static int eraseRadioButton=0x7f080033;
        public static final int eraseRadioButton1=0x7f08003b;
        public static final int eraseRadioButton2=0x7f08003c;
        public static final int eraseRadioButton3=0x7f08003d;
        public static final int eraseRadioButtonClear=0x7f08003e;
        public static int eraseRadioGroup=0x7f08003a;
        public static int freeCropMaskView=0x7f080041;
        public static int free_crop=0x7f080003;
        public static int image_preview=0x7f080047;
        public static int penpreview=0x7f08000a;
        public static int rectCropMaskView=0x7f080042;
        public static int rect_crop=0x7f080043;
        public static int redoView=0x7f080038;
        public static int remove_brush=0x7f080002;
        public static int save_image=0x7f080046;
        public static int save_to_gallery=0x7f080048;
        public static int save_to_omlet=0x7f080049;
        public static int seekbar_Alpha=0x7f08001d;
        public static int seekbar_width=0x7f080011;
        public static int select_brush=0x7f08000f;
        public static int select_brush_name=0x7f08000e;
        public static int select_color=0x7f08001a;
        public static int select_color_name=0x7f080019;
        public static int selectionActionBarLayout=0x7f080040;
        public static int sendView=0x7f080039;
        public static int sl_brush_color_thickness_layout=0x7f08000c;
        public static int stroke_width=0x7f080010;
        public static int undoView=0x7f080037;
    }
    public static final class integer {
        public static int color_picker_height=0x7f060000;
        public static int color_picker_width=0x7f060001;
        public static int screen_size=0x7f060002;
    }
    public static final class layout {
        public static int brush_library_item=0x7f030000;
        public static int cropimage_layout=0x7f030001;
        public static int editor_func_popup_penmenu=0x7f030002;
        public static int gb_draw_mode=0x7f030003;
        public static int gb_erase_popupwindow=0x7f030004;
        public static int gb_main=0x7f030005;
        public static int gb_selection_mode=0x7f030006;
        public static int image_preview_layout=0x7f030007;
        public static int save_action_layout=0x7f030008;
    }
    public static final class string {
        public static int brush_edit_dialog_airbrush=0x7f040000;
        public static int brush_edit_dialog_back=0x7f040001;
        public static int brush_edit_dialog_brush=0x7f040002;
        public static int brush_edit_dialog_full=0x7f04000c;
        public static int brush_edit_dialog_library=0x7f040003;
        public static int brush_edit_dialog_marker=0x7f040004;
        public static int brush_edit_dialog_pen=0x7f040005;
        public static int brush_edit_dialog_pencil=0x7f040006;
        public static int brush_edit_dialog_rollerpen=0x7f040007;
        public static int brush_edit_dialog_save=0x7f040008;
        public static int brush_edit_dialog_save_successful=0x7f04000d;
        public static int brush_edit_dialog_stroke=0x7f04000e;
        public static int editor_pen_dialog_title=0x7f040009;
        public static int graffiti_board=0x7f04000f;
        public static int newto_editor_func_popup_d_brush_alpha=0x7f04000a;
        public static int newto_editor_func_popup_d_brush_stroke=0x7f04000b;
        public static int save_gallery=0x7f040010;
        public static int save_gallery_success=0x7f040011;
        public static int save_omlet=0x7f040012;
        public static int save_omlet_success=0x7f040013;
        public static int save_to=0x7f040014;
        public static int start_your_drawing=0x7f040015;
    }
}
